import { pgTable, uuid, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

/**
 * Schema conventions (see .cursor/rules/backend.mdc and the drizzle-postgres-patterns
 * skill for the full rationale):
 * - Primary keys are UUIDs generated by Postgres (`gen_random_uuid()`).
 * - Every table has `createdAt` / `updatedAt` timestamps.
 * - Table names are plural, snake_case in the database, camelCase in TS.
 */

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: text('email').notNull(),
    passwordHash: text('password_hash').notNull(),
    name: text('name').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex('users_email_unique_idx').on(table.email)],
);

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
